# Generated by Django 4.2.8 on 2026-02-03 21:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('database_type', models.CharField(choices=[('morgue', 'Morgue'), ('jail', 'Jail/Detention'), ('police', 'Police Records'), ('public_records', 'Public Records')], max_length=50)),
                ('organization', models.CharField(max_length=255)),
                ('connection_type', models.CharField(choices=[('rest_api', 'REST API'), ('soap_api', 'SOAP API'), ('database', 'Database'), ('file_sync', 'File Sync')], max_length=20)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('database_host', models.CharField(blank=True, max_length=255)),
                ('database_port', models.IntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=100, help_text='Requests per minute')),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Database',
                'verbose_name_plural': 'External Databases',
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id_field', models.CharField(max_length=255)),
                ('image_url_field', models.CharField(max_length=255)),
                ('name_field', models.CharField(max_length=255)),
                ('date_field', models.CharField(blank=True, max_length=255)),
                ('location_field', models.CharField(blank=True, max_length=255)),
                ('status_field', models.CharField(blank=True, max_length=255)),
                ('custom_field_mappings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='database_integration.externaldatabase')),
            ],
            options={
                'verbose_name': 'Database Schema',
                'verbose_name_plural': 'Database Schemas',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('external_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='database_integration.externaldatabase')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['external_db', 'started_at'], name='database_in_externa_9fa3a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('search', 'Search'), ('fetch', 'Fetch'), ('sync', 'Sync')], max_length=50)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('external_db', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='database_integration.externaldatabase')),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['external_db', 'created_at'], name='database_in_externa_23e1a1_idx'), models.Index(fields=['query_type', 'created_at'], name='database_in_query_t_ae171a_idx')],
            },
        ),
    ]
