export const KENYA_LOCATIONS = {
  "Mombasa": ["Changamwe", "Jomvu", "Kisauni", "Nyali", "Likoni", "Mvita"],
  "Kwale": ["Msambweni", "Lunga Lunga", "Matuga", "Kinango"],
  "Kilifi": ["Kilifi North", "Kilifi South", "Kaloleni", "Rabai", "Ganze", "Malindi", "Magarini"],
  "Tana River": ["Bura", "Galole", "Garsen"],
  "Lamu": ["Lamu East", "Lamu West"],
  "Taita Taveta": ["Taveta", "Wundanyi", "Mwatate", "Voi"],
  "Garissa": ["Garissa Township", "Balambala", "Lagdera", "Dadaab", "Fafi", "Ijara"],
  "Wajir": ["Wajir North", "Wajir East", "Wajir West", "Wajir South", "Tarbaj", "Eldas"],
  "Mandera": ["Mandera East", "Mandera West", "Mandera North", "Mandera South", "Banissa", "Lafey"],
  "Marsabit": ["Saku", "Laisamis", "North Horr", "Moyale"],
  "Isiolo": ["Isiolo North", "Isiolo South"],
  "Meru": ["Igembe South", "Igembe Central", "Igembe North", "Tigania East", "Tigania West", "North Imenti", "Central Imenti", "South Imenti", "Buuri"],
  "Tharaka Nithi": ["Tharaka", "Chuka/Igambang’ombe", "Maara"],
  "Embu": ["Manyatta", "Runyenjes", "Mbeere South", "Mbeere North"],
  "Kitui": ["Kitui Central", "Kitui East", "Kitui West", "Kitui Rural", "Kitui South", "Mwingi North", "Mwingi West", "Mwingi Central"],
  "Machakos": ["Machakos Town", "Mavoko", "Masinga", "Yatta", "Kangundo", "Kathiani", "Matungulu", "Mwala"],
  "Makueni": ["Makueni", "Kilome", "Kaiti", "Kibwezi East", "Kibwezi West"],
  "Nyandarua": ["Kinangop", "Kipipiri", "Ol Kalou", "Ol Jororok", "Ndaragwa"],
  "Nyeri": ["Tetu", "Kieni", "Mathira", "Othaya", "Mukurweini", "Nyeri Town"],
  "Kirinyaga": ["Mwea", "Gichugu", "Ndia", "Kirinyaga Central"],
  "Murang’a": ["Kangema", "Mathioya", "Kiharu", "Kigumo", "Maragwa", "Kandara", "Gatanga"],
  "Kiambu": ["Gatundu South", "Gatundu North", "Juja", "Thika Town", "Ruiru", "Githunguri", "Kiambu Town", "Kiambaa", "Limuru", "Lari", "Kabete", "Kikuyu"],
  "Turkana": ["Turkana North", "Turkana West", "Turkana Central", "Turkana South", "Loima", "Turkana East"],
  "West Pokot": ["Kapenguria", "Sigor", "Kacheliba", "Pokot South"],
  "Samburu": ["Samburu West", "Samburu North", "Samburu East"],
  "Trans-Nzoia": ["Kwanza", "Endebess", "Saboti", "Kiminini", "Cherangany"],
  "Uasin Gishu": ["Soy", "Turbo", "Moiben", "Ainabkoi", "Kapseret", "Kesses"],
  "Elgeyo Marakwet": ["Marakwet East", "Marakwet West", "Keiyo North", "Keiyo South"],
  "Nandi": ["Tinderet", "Aldai", "Nandi Hills", "Chesumei", "Emgwen", "Mosop"],
  "Baringo": ["Tiaty", "Baringo North", "Baringo Central", "Baringo South", "Mogotio", "Eldama Ravine"],
  "Laikipia": ["Laikipia West", "Laikipia East", "Laikipia North"],
  "Nakuru": ["Nakuru Town East", "Nakuru Town West", "Naivasha", "Gilgil", "Subukia", "Rongai", "Bahati", "Molo", "Njoro", "Kuresoi North", "Kuresoi South"],
  "Narok": ["Narok North", "Narok South", "Narok East", "Narok West", "Emurua Dikirr"],
  "Kajiado": ["Kajiado North", "Kajiado East", "Kajiado West", "Kajiado South"],
  "Kericho": ["Kipkelion East", "Kipkelion West", "Ainamoi", "Belgut", "Bureti", "Sigowet/Soin"],
  "Bomet": ["Sotik", "Chepalungu", "Bomet East", "Bomet Central", "Konoin"],
  "Kakamega": ["Lugari", "Likuyani", "Malava", "Lurambi", "Navakholo", "Mumias West", "Mumias East", "Matungu", "Butere", "Khwisero", "Shinyalu", "Ikolomani"],
  "Vihiga": ["Vihiga", "Sabatia", "Hamisi", "Emuhaya", "Luanda"],
  "Bungoma": ["Mt. Elgon", "Sirisia", "Kabuchai", "Bumula", "Kanduyi", "Webuye East", "Webuye West", "Kimilili", "Tongaren"],
  "Busia": ["Teso North", "Teso South", "Nambale", "Matayos", "Butula", "Funyula", "Bunyala"],
  "Siaya": ["Ugenya", "Ugunja", "Alego Usonga", "Gem", "Bondo", "Rarieda"],
  "Kisumu": ["Kisumu East", "Kisumu West", "Kisumu Central", "Seme", "Nyando", "Muhoroni", "Nyakach"],
  "Homa Bay": ["Kasipul", "Kabondo Kasipul", "Karachuonyo", "Rangwe", "Homa Bay Town", "Ndhiwa", "Mbita", "Suba"],
  "Migori": ["Rongo", "Awendo", "Suna East", "Suna West", "Uriri", "Nyatike", "Kuria East", "Kuria West"],
  "Kisii": ["Bonchari", "South Mugirango", "Nyaribari Chache", "Nyaribari Masaba", "Kitutu Chache North", "Kitutu Chache South", "Bobasi", "Bomachoge Borabu", "Bomachoge Chache"],
  "Nyamira": ["Borabu", "North Mugirango", "West Mugirango", "Kitutu Masaba"],
  "Nairobi": ["Westlands", "Dagoretti North", "Dagoretti South", "Lang’ata", "Kibra", "Roysambu", "Kasarani", "Ruaraka", "Embakasi North", "Embakasi East", "Embakasi West", "Embakasi Central", "Embakasi South", "Makadara", "Kamukunji", "Starehe", "Mathare"]
};
