# Generated by Django 4.2.8 on 2026-03-06 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facial_recognition', '0001_initial'),


    ]

    operations = [
        migrations.CreateModel(
            name='SecureChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channel', to='facial_recognition.missingperson')),


                ('participants', models.ManyToManyField(related_name='secure_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secure Channel',
                'verbose_name_plural': 'Secure Channels',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_payload', models.TextField(help_text='End-to-end encrypted message content')),
                ('payload_hash', models.CharField(help_text='SHA-256 hash of the encrypted payload', max_length=64)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.securechannel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encrypted Message',
                'verbose_name_plural': 'Encrypted Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
