# Generated by Django 4.2.8 on 2026-02-03 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacialMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_confidence', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('distance_metric', models.FloatField(blank=True, help_text='Facial distance metric from comparison', null=True)),
                ('source_database', models.CharField(choices=[('morgue', 'Morgue Database'), ('jail', 'Jail Database'), ('police', 'Police Database'), ('user_upload', 'User Upload')], default='user_upload', max_length=20)),
                ('source_reference', models.CharField(help_text='ID/reference from external database', max_length=255)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('verified', 'Verified Match'), ('false_positive', 'False Positive'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('algorithm_version', models.CharField(max_length=50)),
                ('model_name', models.CharField(default='Facenet', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Facial Match',
                'verbose_name_plural': 'Facial Matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacialRecognitionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='facial_recognition/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('image_hash', models.CharField(help_text='SHA256 hash of image for deduplication', max_length=64, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image used for searches')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('face_embedding', models.JSONField(blank=True, null=True)),
                ('face_confidence', models.FloatField(blank=True, help_text='Confidence score that image contains a face', null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facial Recognition Image',
                'verbose_name_plural': 'Facial Recognition Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('searching', 'Searching'), ('found', 'Found'), ('closed', 'Case Closed')], default='reported', max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('last_seen_date', models.DateTimeField(blank=True, null=True)),
                ('last_seen_location', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('identifying_marks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing Persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('retries', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_queue', to='facial_recognition.facialrecognitionimage')),
            ],
            options={
                'verbose_name': 'Processing Queue Item',
                'verbose_name_plural': 'Processing Queue Items',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
