# Generated by Django 5.2.11 on 2026-02-19 05:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_image', models.ImageField(upload_to='search_sessions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('search_query', models.TextField(blank=True, help_text='Optional search parameters')),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('total_candidates_searched', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('closure_action', models.CharField(blank=True, choices=[('save', 'Save for Later'), ('finalize', 'Finalize Match'), ('search_again', 'Search Again'), ('no_match', 'No Match Found')], max_length=20, null=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_sessions', to='facial_recognition.facialmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Session',
                'verbose_name_plural': 'Search Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_closed'], name='facial_reco_user_id_c84c1c_idx'), models.Index(fields=['created_at', 'is_closed'], name='facial_reco_created_923738_idx')],
            },
        ),
    ]
