# Generated by Django 4.2.8 on 2026-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0004_alter_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facialmatch',
            name='requires_human_review',
            field=models.BooleanField(default=False, help_text='Flagged for human review when confidence is borderline (90-98%)'),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='User explicitly confirmed consent before biometric search'),
        ),
    ]
