# Generated by Django 4.2.8 on 2026-02-27 23:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0005_add_hitl_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='dual_signature_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='dual_signature_police',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='emergency_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='jurisdiction',
            field=models.CharField(choices=[('KE', 'Kenya'), ('EU', 'European Union'), ('US', 'United States')], default='KE', max_length=50),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='retention_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facialmatch',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('MATCH_FOUND', 'Match Found'), ('PENDING_CLOSURE', 'Pending Closure'), ('CLOSED', 'Closed'), ('NO_MATCH', 'No Match')], default='reported', max_length=20),
        ),
        migrations.CreateModel(
            name='BiometricEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', models.JSONField(help_text='512-dimensional facial embedding vector')),
                ('voice_print', models.BinaryField(blank=True, null=True)),
                ('image_quality_score', models.FloatField(default=0.0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purge_after', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_embeddings', to='facial_recognition.missingperson')),
            ],
            options={
                'verbose_name': 'Biometric Embedding',
                'verbose_name_plural': 'Biometric Embeddings',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
