# Generated by Django 4.2.8 on 2026-03-06 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facial_recognition', '0006_missingperson_dual_signature_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurisdictionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_code', models.CharField(help_text='e.g., KE, EU, US', max_length=10, unique=True)),
                ('default_retention_policy', models.CharField(choices=[('standard', 'Standard (30 days)'), ('criminal', 'Criminal (5 years)')], default='standard', max_length=20)),
                ('standard_retention_days', models.IntegerField(default=30)),
                ('criminal_retention_days', models.IntegerField(default=1825)),
            ],
            options={
                'verbose_name': 'Jurisdiction Config',
                'verbose_name_plural': 'Jurisdiction Configs',
            },
        ),
        migrations.AddField(
            model_name='missingperson',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='government_analysis_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='police_analysis_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='retention_policy_type',
            field=models.CharField(choices=[('standard', 'Standard (30 days)'), ('criminal', 'Criminal (5 years)')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('RAISED', 'Raised to Police'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('ANALYZED', 'Analyzed by Police'), ('ESCALATED', 'Escalated to Government'), ('GOVERNMENT_REVIEW', 'In Government Review'), ('MATCH_FOUND', 'Match Found'), ('PENDING_CLOSURE', 'Pending Closure'), ('CLOSED', 'Closed'), ('NO_MATCH', 'No Match')], default='REPORTED', max_length=20),
        ),
        migrations.CreateModel(
            name='OfflineSignatureQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_payload', models.JSONField(help_text='Cryptographic signature data (WebAuthn/FIDO2)')),
                ('signed_at', models.DateTimeField(help_text='When the signature was created offline')),
                ('nonce', models.CharField(help_text='Unique nonce to prevent replay attacks', max_length=64, unique=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('requires_manual_review', models.BooleanField(default=False, help_text='Flagged true if case was modified online while offline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_signatures', to='facial_recognition.missingperson')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offline Signature',
                'verbose_name_plural': 'Offline Signatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
