# Generated by Django 4.2.8 on 2026-03-06 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facial_recognition', '0007_jurisdictionconfig_missingperson_escalated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='case_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
