# Generated by Django 4.2.8 on 2026-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0008_missingperson_assigned_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facialmatch',
            name='source_database',
            field=models.CharField(choices=[('morgue', 'Morgue Database'), ('jail', 'Jail Database'), ('police', 'Police Database'), ('user_upload', 'User Upload'), ('training_dataset', 'Training Dataset')], default='user_upload', max_length=20),
        ),
    ]
