# Generated by Django 4.2.8 on 2026-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0009_alter_facialmatch_source_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('RAISED', 'Raised to Police'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('ANALYZED', 'Analyzed by Police'), ('ESCALATED', 'Escalated to Government'), ('GOVERNMENT_REVIEW', 'In Government Review'), ('MATCH_FOUND', 'Match Found'), ('PENDING_CLOSURE', 'Pending Closure'), ('CLOSED', 'Closed'), ('NO_MATCH', 'No Match'), ('TRAINING_DATASET', 'Training Dataset')], default='REPORTED', max_length=20),
        ),
    ]
