# Generated by Django 4.2.8 on 2026-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0010_alter_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='complexion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='eye_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='height_unit',
            field=models.CharField(choices=[('inches', 'Inches'), ('ft', 'Feet'), ('meters', 'Meters')], default='inches', max_length=10),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='languages',
            field=models.TextField(blank=True, help_text='Comma-separated list of languages'),
        ),
    ]
