# Generated by Django 4.2.8 on 2026-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0011_missingperson_complexion_missingperson_eye_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facialrecognitionimage',
            name='image_hash',
            field=models.CharField(db_index=True, help_text='SHA256 hash of image for deduplication (not unique to allow re-uploads for testing)', max_length=64),
        ),
    ]
