# Generated by Django 4.2.8 on 2026-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0012_alter_facialrecognitionimage_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='ob_number',
            field=models.CharField(blank=True, help_text='Police OB-Number (e.g., OB-123456/3-26)', max_length=50, null=True),
        ),
    ]
