# Generated by Django 4.2.8 on 2026-03-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0013_missingperson_ob_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='police_station',
            field=models.CharField(blank=True, help_text='Police Station where reported', max_length=150, null=True),
        ),
    ]
