# Generated by Django 4.2.8 on 2026-02-03 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facial_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_missing_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facialrecognitionimage',
            name='missing_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_recognition_images', to='facial_recognition.missingperson'),
        ),
        migrations.AddField(
            model_name='facialmatch',
            name='missing_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_matches', to='facial_recognition.missingperson'),
        ),
        migrations.AddField(
            model_name='facialmatch',
            name='source_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='facial_recognition.facialrecognitionimage'),
        ),
        migrations.AddField(
            model_name='facialmatch',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='processingqueue',
            index=models.Index(fields=['status', 'priority'], name='facial_reco_status_4f6a05_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['status', 'date_reported'], name='facial_reco_status_a78d65_idx'),
        ),
        migrations.AddIndex(
            model_name='facialmatch',
            index=models.Index(fields=['missing_person', 'status'], name='facial_reco_missing_69c859_idx'),
        ),
        migrations.AddIndex(
            model_name='facialmatch',
            index=models.Index(fields=['match_confidence', 'created_at'], name='facial_reco_match_c_c45a0b_idx'),
        ),
    ]
