# Generated by Django 4.2.8 on 2026-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0003_searchsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('searching', 'Searching'), ('found', 'Found'), ('closed', 'Case Closed'), ('escalated', 'Escalated'), ('zoom_required', 'Zoom Required')], default='reported', max_length=20),
        ),
    ]
