# Generated by Django 5.2.11 on 2026-02-20 10:05

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='government_position',
            field=models.CharField(blank=True, choices=[('cs', 'CS'), ('ps', 'PS'), ('security_officer', 'Security Officer'), ('other', 'Other - specify')], help_text='Government position for Government Officials', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='government_security_id',
            field=models.CharField(blank=True, help_text='8-digit Government Security ID for Government Officials', max_length=8, null=True, validators=[users.models.validate_eight_digits]),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='8-digit National ID for Family Members', max_length=8, null=True, validators=[users.models.validate_eight_digits]),
        ),
        migrations.AddField(
            model_name='user',
            name='police_rank',
            field=models.CharField(blank=True, choices=[('corporal', 'Corporal'), ('lieutenant', 'Lieutenant'), ('general', 'General'), ('base_commander', 'Base Commander'), ('ocs', 'OCS'), ('ocpd', 'OCPD'), ('ig', 'IG')], help_text='Police rank for Police Officers', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position_specify',
            field=models.CharField(blank=True, help_text='Specify position if "Other" is selected', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='service_id',
            field=models.CharField(blank=True, help_text='8-digit Service ID for Police Officers', max_length=8, null=True, validators=[users.models.validate_eight_digits]),
        ),
    ]
