# Generated by Django 4.2.8 on 2026-02-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_government_position_user_government_security_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_hash',
            field=models.CharField(blank=True, help_text='Privacy-preserving hash of the user ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jurisdiction',
            field=models.CharField(choices=[('KE', 'Kenya'), ('EU', 'European Union'), ('US', 'United States')], default='KE', help_text='User jurisdiction for data residency compliance', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
