# Generated by Django 4.2.8 on 2026-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog_actor_hash_auditlog_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='police_rank',
            field=models.CharField(blank=True, choices=[('ig', 'Inspector-General (IG)'), ('dig', 'Deputy Inspector-General (DIG)'), ('saig', 'Senior Assistant Inspector-General (SAIG)'), ('aig', 'Assistant Inspector-General (AIG)'), ('ssp', 'Senior Superintendent of Police (SSP)'), ('sp', 'Superintendent of Police (SP)'), ('asp', 'Assistant Superintendent of Police (ASP)'), ('ci', 'Chief Inspector (CI)'), ('ip', 'Inspector of Police (IP)'), ('ssgt', 'Senior Sergeant (SSgt)'), ('sgt', 'Sergeant (Sgt)'), ('cpl', 'Corporal (Cpl)'), ('constable', 'Constable')], help_text='Police rank for Police Officers', max_length=50, null=True),
        ),
    ]
