# Generated by Django 6.0.3 on 2026-03-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('search', 'Search'), ('match_found', 'Match Found'), ('data_access', 'Data Access'), ('user_login', 'User Login'), ('api_call', 'API Call'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('ADMIN_LOGOUT', 'Admin Logout')], max_length=20),
        ),
    ]
